name = "TheBackrooms Breakout"
author = "tbbk-team"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31e945a7d88b7a5b847a454aed592dbd8ec5761ba745b47582e1a22751d1d082"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
