name = "TheBackrooms Breakout"
author = "tbbk-team"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a79173c918545b319a0fa0c8e7cc8b6ebde2940ff1d77dec7ce0c63c9c6d0bb9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
