name = "TheBackrooms Breakout"
author = "tbbk-team"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "418fa8a404d0038806189f7902f4327494dede7530d89aabc042429bd70df2ca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
